remote_theme: pages-themes/time-machine@v0.2.0
plugins:
  - jekyll-remote-theme

title: Yodabytz
description: Novice Python Programmer Exploring Code and Tech.
show_downloads: true

google_analytics: [G-GBPX28J07V]
