    ```yml
    remote_theme: pages-themes/time-machine@v0.2.0
    plugins:
    - jekyll-remote-theme # add this line to the plugins list if you already have one
    ```

title: Yodabytz
description: Novice Python Programmer Exploring Code and Tech.
show_downloads: true
google_analytics:
theme: jekyll-theme-time-machine